version: "2"

linters:
  enable:
    - nolintlint
  # disable:
  #  - staticcheck
  #  - errcheck
  exclusions:
    paths:
      - third-party

formatters:
  enable:
    - gofmt

issues:
  max-issues-per-linter: 0
  max-same-issues: 0